#step 1 download web page and extract rashi bhavishya 
from playwright.sync_api import sync_playwright
from bs4 import BeautifulSoup
from gtts import gTTS
import pygame

with sync_playwright() as p:
    url = "https://www.amarujala.com/astrology/horoscope/aries-daily-horoscope"
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    
    # Change wait_until to domcontentloaded or load
    page.goto(url, wait_until="domcontentloaded")
    
    html = page.content()
    browser.close()
    
    soup = BeautifulSoup(html, 'html.parser')    
    
    # Using text or get_text() is safer than .string if there are inner tags
    h1_element = soup.find('h1', class_='rashih1')
    desc_element = soup.find('div', class_='desc')
    
    heading = h1_element.get_text(strip=True)
    text = desc_element.get_text(strip=True)

#step 2 convert this text into audio using tts 
tts = gTTS(text=heading + " " + text, lang='hi')
tts.save("voice.mp3")

#step 3 play audio generated by TTS
pygame.init()
pygame.mixer.init()

#music load
pygame.mixer.music.load("voice.mp3")
#music play 
pygame.mixer.music.play()

#program will wait to finish until sound is played
while pygame.mixer.music.get_busy():
    pygame.time.Clock().tick(10)
    # print("playing sound...")

print("program finished...")